line-length = 100
select = ["ALL"]
ignore = [
    "ERA001",  # Commented out code
    "T201",    # print() found
    "PLR2004", # Magic number
    "D",       # Missing docstring
    "PTH",     # Pathlib should be used over os.path
]
