services:
  frontend:
    image: phyke/ml2025-carprice-sveltekit
    ports:
      - "80:80"
    environment:
      - ORIGIN=http://localhost:80
    depends_on:
      - backend

  backend:
    image: phyke/ml2025-carprice-fastapi
    env_file:
      - .env
