services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - ORIGIN=http://localhost:80
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - .env
