services:
  frontend:
    build: ./frontend
    container_name: frontend
    # ports:
    # - "3000:3000"
    environment:
      - ORIGIN=http://localhost:8080
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    # ports:
    #   - "5000:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
