services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - ORIGIN=http://localhost:3000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    # ports:
    #   - "5000:5000"
