services:
  backend:
    image: phyke/ml2025-carprice-fastapi

  web:
    image: phyke/ml2025-carprice-sveltekit
    # ports:
    # - "80:80"
    environment:
      - ORIGIN=https://web-st125923.ml.brain.cs.ait.ac.th
    env_file:
      - .env
    depends_on:
      - backend
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.web-st125923.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is <service_name>-<folder_name>
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.web-st125923.rule=Host(`st125923.ml.brain.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.web-st125923.tls=true
      - traefik.http.routers.web-st125923.tls.certresolver=production
      - traefik.http.routers.web-st125923.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true
